# -*- coding: utf-8 -*-
"""Supernan project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLRSlWqiJuUUF2oFyJVR3WTB_2UEqzxu
"""

# Update system package list
!apt-get update

# Install required system tools:
# ffmpeg → audio/video processing
# git → cloning repositories (optional but useful)
!apt-get install -y ffmpeg git


# Install Python dependencies:
# openai-whisper → speech recognition (ASR)
# transformers & accelerate → model loading support (TTS / future models)
# scipy & soundfile → audio reading/writing
# librosa → optional audio processing utilities
!pip install -q openai-whisper transformers accelerate scipy soundfile librosa

# Import Colab file upload utility
from google.colab import files

# Upload input files (e.g., video or audio) from local system to Colab environment
files.upload()

# Convert video to audio
!ffmpeg -y -i clip.mp4 -vn -acodec pcm_s16le -ar 16000 -ac 1 clean.wav

# Install Whisper ASR
!pip install -q openai-whisper

# Import Whisper speech recognition library
import whisper

# Load the Whisper Large-v3 model (high-accuracy ASR for multilingual speech)
model = whisper.load_model("large-v3")

# Confirm model is loaded successfully
print("Model loaded")

# Transcribe Kannada speech from audio file using Whisper
result = model.transcribe(
    "clean.wav",        # Input audio file
    language="kn",      # Force Kannada language detection
    task="transcribe",  # Speech-to-text (not translation)
    temperature=0       # Deterministic output for higher consistency
)

# Extract transcribed text from result dictionary
kannada_text = result["text"]

# Display the recognized Kannada text
print("Kannada Text:")
print(kannada_text)

# Import utility to play audio inside the notebook
from IPython.display import Audio

# Play the extracted audio file to verify speech quality
Audio("clean.wav")

# Install required libraries for multilingual translation models
# transformers → model loading and inference
# sentencepiece → tokenizer dependency for many NLP models
# torch → deep learning framework used by the models
!pip install -q transformers sentencepiece torch

# Install Hugging Face Hub library for model authentication and downloads
!pip install -q huggingface_hub

# Import login utility to authenticate with Hugging Face account
from huggingface_hub import login

# Login using personal access token (required for gated or large models)
login()

# Install NLP dependencies required for translation models
# transformers → model loading and inference
# sentencepiece → tokenizer support for multilingual models
!pip install -q transformers sentencepiece

# Import translation model utilities
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load multilingual translation model (supports Kannada → Hindi)
model_name = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("Model loaded ✅")


# Kannada text from Whisper
input_text = kannada_text

# Tokenize input text
inputs = tokenizer(input_text, return_tensors="pt")

# Generate Hindi translation
translated_tokens = model.generate(
    **inputs,
    forced_bos_token_id=tokenizer.convert_tokens_to_ids("hin_Deva"),
    max_length=256
)

# Decode translated tokens into readable text
hindi_text = tokenizer.batch_decode(
    translated_tokens,
    skip_special_tokens=True
)[0]

print("Hindi Translation:")
print(hindi_text)

# Install neural text-to-speech library and async compatibility helper
# edge-tts → high-quality neural voice synthesis
# nest_asyncio → allows async execution inside notebook environments (e.g., Colab)
!pip install -q edge-tts nest_asyncio

# Enable nested async loops (required for running async code in Colab)
import nest_asyncio
nest_asyncio.apply()

# Import async framework and Edge TTS library
import asyncio
import edge_tts

# Hindi text to be converted into speech
text = hindi_text

# Select Hindi female neural voice
voice = "hi-IN-SwaraNeural"   # Female Hindi voice

# Async function to generate speech audio
async def generate_audio():
    communicate = edge_tts.Communicate(text=text, voice=voice)
    await communicate.save("hindi.wav")

# Run audio generation
await generate_audio()

print("Hindi audio generated ✅")

# Import video and audio processing utilities
from moviepy.editor import VideoFileClip, AudioFileClip

# Load original video and generated Hindi audio
video = VideoFileClip("clip.mp4")
audio = AudioFileClip("hindi.wav")

# Trim audio if longer than video
audio = audio.subclip(0, video.duration)

# Replace original audio with generated Hindi speech
final = video.set_audio(audio)

# Export final dubbed video
final.write_videofile(
    "final_dubbed.mp4",
    codec="libx264",
    audio_codec="aac"
)

print("Final video ready ✅")

# Import utility to display video inside the notebook
from IPython.display import Video

# Play the final dubbed video output
Video("final_dubbed.mp4")

# Import file download utility for Colab
from google.colab import files

# Import file download utility for Colab
files.download("final_dubbed.mp4")

# List all files in the current working directory
# Useful for verifying that output files were created successfully
!ls

